/*
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

                1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
*/
#include <iostream>
using namespace std;

int fib(int n) {
    if (n == 1)         return 1;
    else if (n == 2)    return 2;
    else if (n > 2)     return fib(n - 1) + fib(n - 2);
    else return 0;
}

int main() {
    int sum = 0;
    for (int i = 1; fib(i) < 4000000; i++) {
        if (!(fib(i) & 1))  sum += fib(i);  // 二进制的最后一位是0的话那么就为偶数。是1的话就为奇数
    }
    cout << sum << endl;
    return 0;
}